name: Navigator Issue Report
description: File a report for anaconda-navigator
labels: ["pkg-navigator"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue! Please fill out the following template in full.

        A few things to keep in mind:
        - This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.
        - For conda issues, you should open an issue at [conda repo](https://github.com/conda/conda/issues)
        - For conda-build issues, you should open an issue at [conda-build repo](https://github.com/conda/conda-build)
        - For an issue with a particular conda-forge package, you should open an issue on the corresponding [feedstock](https://github.com/conda-forge) 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please tell us, what kind of problem you experienced with Anaconda-Navigator?
      placeholder: |
         We encourage you to use all provided by GitHub tools to add as many details as possible: 
          - Please describe an actual behavior and steps to reproduce it.
          - Attach screenshots if the issue is any UI artifact. 
          - Specify steps that lead to the spotted issue.
          - Please copy and paste the output of `anaconda-navigator --debug`
    validations:
      required: true
  - type: textarea
    id: conda-info
    attributes:
      label: "`conda info` output"
      description: "Please copy and paste the output of `conda info` command"
      render: shell
    validations:
      required: true
  - type: textarea
    id: conda-list
    attributes:
      label: "`conda list -n base --show-channel-urls` output"
      description: "Please copy and paste the output of `conda list -n base --show-channel-urls` command"
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.anaconda.com/community-code-of-conduct/).
      options:
        - label: I agree to follow [Anaconda Community Code of Conduct](https://www.anaconda.com/community-code-of-conduct/).
          required: true
