name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    name: Test
    services:
      mongodb_primary:
        image: bitnami/mongodb:4.2
        ports:
          - "27017:27017"
        env:
          MONGODB_REPLICA_SET_MODE: primary
          MONGODB_ROOT_PASSWORD: password123
          MONGODB_REPLICA_SET_KEY: replicasetkey123
      mongodb_secondary:
        image: bitnami/mongodb:4.2
        ports:
          - "27018:27017"
        env:
          MONGODB_REPLICA_SET_MODE: secondary
          MONGODB_INITIAL_PRIMARY_HOST: mongodb_primary
          MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
          MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: password123
          MONGODB_REPLICA_SET_KEY: replicasetkey123
    permissions: read-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh

      - name: Install pymongo
        run: |
          conda install --yes pymongo

      - name: Run tests
        run: |
          python /home/runner/work/test/test/main.py
        env:
          ANACONDA_MONGO_URL_TESTING: mongodb://root:password123@mongodb_primary:27017,mongodb_secondary:27018/?replicaSet=replicaset
